#!/usr/bin/env node
// Hourly SpaceX launch monitor. Detects upcoming launches and generates
// time-sensitive tweet drafts (T-24h, T-1h, post-launch). Tracks announced
// launches in marketing/launches-state.json so we don't repeat ourselves.
import { readFileSync, writeFileSync, existsSync, appendFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { templates, renderTweet } from "./templates.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..", "..");
const statePath = resolve(root, "marketing", "launches-state.json");
const draftsDir = resolve(root, "marketing", "drafts");

const SPACEX_LSP = 121;
const LL = "https://ll.thespacedevs.com/2.2.0/launch";

function loadJson(path, fallback) {
  if (!existsSync(path)) return fallback;
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return fallback; }
}

async function fetchUpcoming() {
  try {
    const res = await fetch(
      `${LL}/upcoming/?lsp__id=${SPACEX_LSP}&ordering=net&limit=5&mode=list`,
      { signal: AbortSignal.timeout(10000), headers: { Accept: "application/json" } }
    );
    if (!res.ok) return [];
    const json = await res.json();
    return json.results || [];
  } catch {
    return [];
  }
}

async function fetchRecentSuccess() {
  try {
    const res = await fetch(
      `${LL}/?lsp__id=${SPACEX_LSP}&status=3&ordering=-net&limit=3&mode=list`,
      { signal: AbortSignal.timeout(10000), headers: { Accept: "application/json" } }
    );
    if (!res.ok) return [];
    const json = await res.json();
    return json.results || [];
  } catch {
    return [];
  }
}

function hoursUntil(iso) {
  return (new Date(iso).getTime() - Date.now()) / (1000 * 60 * 60);
}

function appendDraft(date, blocks) {
  if (!existsSync(draftsDir)) mkdirSync(draftsDir, { recursive: true });
  const path = resolve(draftsDir, `${date}-launches.md`);
  const header = existsSync(path)
    ? ""
    : `# Launch alerts — ${date}\n\nAuto-generated by launch monitor.\n\n`;
  const body = header + blocks.join("\n");
  writeFileSync(path, existsSync(path) ? readFileSync(path, "utf8") + body : body);
  return path;
}

async function main() {
  const state = loadJson(statePath, { announced: {} });
  const today = new Date().toISOString().slice(0, 10);
  const tweetsToWrite = [];
  const newAnnouncements = { ...state.announced };

  const upcoming = await fetchUpcoming();
  for (const launch of upcoming) {
    const hrs = hoursUntil(launch.net);
    const id = launch.id;
    const launchPad = launch.pad?.name ?? "unknown pad";
    const key24 = `${id}:t24`;
    const key1 = `${id}:t1`;

    if (hrs > 0 && hrs <= 25 && hrs > 22 && !newAnnouncements[key24]) {
      tweetsToWrite.push(templates.launchImminent({
        launchName: launch.name,
        hoursAway: Math.round(hrs),
        launchPad,
      }));
      newAnnouncements[key24] = today;
    }

    if (hrs > 0 && hrs <= 1.5 && !newAnnouncements[key1]) {
      tweetsToWrite.push(templates.launchT1h({
        launchName: launch.name,
        launchPad,
      }));
      newAnnouncements[key1] = today;
    }
  }

  const recent = await fetchRecentSuccess();
  for (const launch of recent) {
    const hrs = hoursUntil(launch.net);
    if (hrs > -24 && hrs < 0) {
      const keySuccess = `${launch.id}:success`;
      if (!newAnnouncements[keySuccess]) {
        const launchDate = new Date(launch.net).toLocaleDateString("en-US", {
          month: "short", day: "numeric",
        });
        tweetsToWrite.push(templates.launchSuccess({
          launchName: launch.name,
          launchDate,
          launchPad: launch.pad?.name ?? "unknown pad",
        }));
        newAnnouncements[keySuccess] = today;
      }
    }
  }

  let draftPath = null;
  if (tweetsToWrite.length > 0) {
    const blocks = tweetsToWrite.map((t) => renderTweet(t));
    draftPath = appendDraft(today, blocks);
  }

  writeFileSync(statePath, JSON.stringify({ announced: newAnnouncements }, null, 2));

  const summary = `${tweetsToWrite.length} launch tweet${tweetsToWrite.length === 1 ? "" : "s"}${draftPath ? " → " + draftPath.replace(root + "/", "") : ""}`;
  console.log(summary);

  const out = process.env.GITHUB_OUTPUT;
  if (out) {
    appendFileSync(out, [
      `tweet_count=${tweetsToWrite.length}`,
      `summary=${summary}`,
      draftPath ? `draft_path=${draftPath.replace(root + "/", "")}` : "draft_path=",
    ].join("\n") + "\n");
  }
}

main().catch((err) => {
  console.error("Launch monitor failed:", err);
  process.exit(1);
});
